name: Scheduled Item Insert

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  run-iteminsert:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq (for parsing JSON)
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Invoke itemInsertAll repeatedly
        run: |
          cursor=0
          while true; do
            response=$(curl -s -X POST -H "cursor: $cursor" "https://ebay-app-drab.vercel.app/api/itemInsertAll")
            echo "Response: $response"
            
            hasMore=$(echo $response | jq '.hasMore')
            if [ "$hasMore" != "true" ]; then
              echo "No more items to process."
              break
            fi

            cursor=$(echo $response | jq '.nextCursor')
          done
        shell: bash
