name: Scheduled Item Insert

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch: # Allows manual triggering

jobs:
  run-iteminsert:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke itemInsert API
        run: curl -X POST "https://ebay-app-drab.vercel.app/api/itemInsertAll"
